spring:
  datasource:
    url: ${{DATABASE_URL}}
    username: ${{DATABASE_USERNAME}}
    password: ${{DATABASE_PWD}}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${{CLIENT_ID}}
            clientSecret: ${{CLIENT_SECRET}}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 443
