spring:
  datasource:
    url: ${{database_url}}
    username: ${{database_username}}
    password: ${{database_pwd}}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${{github_client_id}}
            clientSecret: ${{github_client_secret}}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG
